[package]
name = "indexedRAG"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.0"
egui = "0.21.0"
directories = "5.0.0"
rusqlite = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
